# define schema version
version: "3.7"
# list of containers to run as part of the app
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    # command to run on start
    command: npm start
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    # envirnonment variables
    env_file:
      - .env
    # ports mapping
    ports:
      - 3000:3000
