# define schema version
version: "3.7"
# list of containers to run as part of the app
services:
  client:
    container_name: yorknews-client-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    # command to run on start
    command: serve -s build -l 3000
    # envirnonment variables
    env_file:
      - .env
    # ports mapping
    ports:
      - 80:3000
