export { default as Home } from "./Home"
export { default as BecomeEditor } from "./BecomeEditor"
export { default as SignUp } from "./SignUp"
export { default as SignIn } from "./SignIn"
export { default as News } from "./News"
export { default as Profile } from "./Profile"
