export { Home } from "./home"
export { default as BecomeEditor } from "./BecomeEditor"
export { default as SignUp } from "./SignUp"
export { default as SignIn } from "./SignIn"
export { default as News } from "./News"
export { default as Profile } from "./Profile"
export { default as CreateNews } from "./CreateNews"
export { default as EditNews } from "./EditNews"
export { default as Error } from "./Error"
export { default as SearchResult } from "./SearchResult"
export { default as ForgotPassword } from "./ForgotPassword"
export { default as ResetPassword } from "./ResetPassword"
